services:
  shard1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRIMS_LISTEN_ADDRESS: /ip4/0.0.0.0/tcp/7001
      PRIMS_SEED_NODES: ""
    ports:
      - "7001:7001"

  shard2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRIMS_LISTEN_ADDRESS: /ip4/0.0.0.0/tcp/7001
      PRIMS_SEED_NODES: ""
    ports:
      - "7002:7001"
    depends_on:
      - shard1

  shard3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PRIMS_LISTEN_ADDRESS: /ip4/0.0.0.0/tcp/7001
      PRIMS_SEED_NODES: ""
    ports:
      - "7003:7001"
    depends_on:
      - shard1
      - shard2
